[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'Xvfb :0 -screen 0 1024x768x16 & sleep 5 && gunicorn run:app --bind 0.0.0.0:$PORT'"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
PORT = "5000"
