name: Deploy Excel Converter API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create web.config
      run: |
        echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
        <configuration>
          <system.webServer>
            <handlers>
              <add name=\"PythonHandler\" path=\"*\" verb=\"*\" modules=\"FastCgiModule\" scriptProcessor=\"D:\Python39\python.exe|D:\Python39\Lib\site-packages\wfastcgi.py\" resourceType=\"Unspecified\" requireAccess=\"Script\" />
            </handlers>
          </system.webServer>
          <appSettings>
            <add key=\"PYTHONPATH\" value=\"D:\home\site\wwwroot\" />
            <add key=\"WSGI_HANDLER\" value=\"run.app\" />
          </appSettings>
        </configuration>" > web.config

    - name: Deploy to Azure Web Apps
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
